package TP.Noyeau;
public enum wilayas {
 ADRAR ,CHLEF, LAGHOUAT, OUMBOUAGHI, BATNA, BEJAIA, BISKRA,BECHAR, BLIDA, BOUIRA, TAMANRASSET, TEBESSA, TLEMCEN, TIARET, TIZIOUZOU, ALGER, DJELFA,JIJEL, SETIF, SAIDA, SKIKDA, SIDIBELABBES, ANNABA, GUELMA, CONSTANTINE, MEDEA, MOSTAGANEM, MSILA, MASCARA,OUARGLA, ORAN, ELBAYDH, ILLIZI,BORDJBOUARRERIDJ,BOUMERDES,ELTAREF,TINDOUF, TISSEMSILT, ELOUED, KHENCHLA, SOUKAHRASS, TIPAZA, MILA, AINDEFLA,NAAMA, AINTEMOUCHENT, GHARDAIA, RELIZANE
}
